plugins {
  id 'org.jetbrains.kotlin.multiplatform' version '2.3.0'
}

repositories {
  mavenCentral()
}

kotlin {
  js(IR) {
    browser()
    binaries.executable()
  }

  sourceSets {
    jsMain {
      kotlin.srcDir("src/main/kotlin")
      resources.srcDir("src/main/resources")
      dependencies {
        implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
      }
    }
  }
}
