plugins {
  alias(libs.plugins.kotlin.multiplatform)
}

repositories {
  mavenCentral()
}

kotlin {
  js(IR) {
    browser()
    binaries.executable()
  }

  sourceSets {
    jsMain {
      kotlin.srcDir("src/main/kotlin")
      resources.srcDir("src/main/resources")
      dependencies {
        implementation libs.coroutines.core
      }
    }
  }
}

def externalScriptsEnabled = providers.gradleProperty("enableExternalScripts").map { it == "true" }.orElse(false)
def externalScriptsFile = file("src/main/resources/external-scripts.html")
def externalScriptsMarker = "@EXTERNAL_SCRIPTS@"

tasks.withType(ProcessResources).configureEach {
  filesMatching("index.html") {
    def scripts = externalScriptsEnabled.get() ? externalScriptsFile.getText("UTF-8") : ""
    filter { line -> line.replace(externalScriptsMarker, scripts) }
  }
}
